### ISSUE TITLE
Error with O3X: Intrinsic parameter is not supported by Device

### ISSUE THREAD

**Issue by pfrydlewicz** [lovepark/ifm3d-pcl-viewer#2]
Hi,
I wanted to try out the pcl viewer with my O3X (FW 1.0.126), but I get following error message:

Lib: Intrinsic parameter is not supported by Device.

I have ifm3d version 0.11.0 installed.

As far as I understand, the intrinsic parameters are only available for O3D, right?

Thanks,
Paul

**Comment by tpanzarella** [comment]
Thanks for reporting this. It is indeed a bug. The fix (which we can issue early this week ... I"m not in position to deal with it today) is on [this line](https://github.com/lovepark/ifm3d-pcl-viewer/blob/master/src/bin/ifm3d-pcl-viewer.cpp#L43) where the PCIC scheme explicitly turns on all images which will include the intrinsics as of `0.11.0`. The fix will be to set a more reasonable PCIC schema for viewing purposes. For now, I'd suggest you either change that line yourself (turn off the intrinsics ... for example) or just use ifm3d `0.10.x` until we patch this for compatibility with `0.11.0`.

Sorry for the inconvenience.

**Comment by pfrydlewicz** [comment]
No worries, I can use the O3D in the meantime.
so actually it's a ifm3d lib issue, right?
(So I can close that request here...)

**Comment by tpanzarella** [comment]
I think the answer is "it depends". @graugans (and his team) implemented the integration of the intrinsics feature to `ifm3d`. [Here](https://github.com/lovepark/ifm3d/commit/c7717723a2771ea44843b83e1b9ac2d22d92369e#diff-1c5c693d5debb7040782e98f6a32b199R376) they explicitly consider this a "hard error", so, for now we can leave it that way. Whether or not to *keep* it that way, I think is a separate discussion. For example, one could argue it should be handled as we handle the lack of an ambient light image on the O3D [here](https://github.com/lovepark/ifm3d/blob/master/modules/framegrabber/src/libifm3d_framegrabber/frame_grabber_impl.hpp#L416). Or maybe something in between: silently fix the "error" but emit loud warnings in the log? 

In the meantime, a fix can be made in this project to only stream back the Cartesian data + amplitude (for pixel coloring) since that is all the PCL viewer is currently capable of displaying (IIRC).
